apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-monitor
  labels:
    release: kube-prometheus-stack
    app: todolist
spec:
  selector:
    matchLabels:
      app: todoapp
    jobLabel: app
  endpoints:
    - port: http
      path: /metrics
      interval: 10s
